name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: latest
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Project
      run: pnpm run dev
    - name: Wait for Project
      run: npx wait-on http://localhost:3000
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30